name: "Setup Node.js, Bun, and install dependencies"

inputs:
    node-version:
        description: "Node.js version to use"
        required: false
        default: "20.12.2"
    bun-version:
        description: "Bun version to use"
        required: false
        default: "1.1.19"
    working-directory:
        description: "Working directory to run the command in"
        required: false
        default: "."

runs:
    using: "composite"
    steps:
        - name: Log inputs
          shell: bash
          run: |
              echo "Node.js version: ${{ inputs.node-version }}"
              echo "Bun version: ${{ inputs.bun-version }}"
              echo "Working directory: ${{ inputs.working-directory }}"

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}

        - name: Install Bun
          uses: oven-sh/setup-bun@v1
          with:
              bun-version: ${{ inputs.bun-version }}

        - name: Install dependencies
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: bun install --frozen-lockfile 