name: CI-CD-MAIN

on:
    push:
        branches:
            - main

env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

permissions:
    contents: write
    pull-requests: write

jobs:
    build-and-test:
        name: build & test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js, Bun, and install dependencies
              uses: ./.github/actions/bun-setup
              with:
                  node-version: "20.12.2"
                  bun-version: "1.1.19"
                  install-args: "--frozen-lockfile"

            - name: Build all
              run: bun run build

            - name: Test all
              run: bun run test

    release-or-create-release-pr:
        name: Release
        runs-on: ubuntu-latest
        needs: [build-and-test]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js, Bun, and install dependencies
              uses: ./.github/actions/bun-setup
              with:
                  node-version: "20.12.2"
                  bun-version: "1.1.19"
                  install-args: "--frozen-lockfile"

            - name: Create Release Pull Request or Publish
              uses: changesets/action@v1
              with:
                  commit: "Release packages"
                  title: "Release packages"
                  publish: bun run change:publish
                  version: bun run change:version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}